### ISSUE TITLE
Support new dynamically linked binary apt and yum repos

### ISSUE THREAD

**Issue by djdefi** [someara/chef-docker#345]
Announcement here: https://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by someara** [comment]
Linking to #394

**Comment by JamesAwesome** [comment]
@st-isidore-de-seville / @someara Any updates on this issue?

I'm hitting a snag with a production app and could really use that dynamically linked docker binary. I'd be willing to help out with a PR but I don't want to duplicate work if you guys have something in motion. :smiley:

**Comment by st-isidore-de-seville** [comment]
hey @JamesAwesome, I was working on creating cookbooks that would link to their repositories and it should be done by tonight.  That being said, once I turn that over to @someara, I guess we will have to evaluate how that fits into his overall cookbook.  I imagine that there is probably some refactoring that has to occur but I do not want to speak for him.

**Comment by JamesAwesome** [comment]
Thank you for the update :+1:

**Comment by st-isidore-de-seville** [comment]
@JamesAwesome: I was having trouble with testing and travis-ci and did not get as far as I planned to.  the yum-docker cookbook: https://github.com/st-isidore-de-seville/cookbook-yum-docker/tree/initial which takes care of the yum docker repos is almost finished and I am trying to have the apt docker repo cookbook finished shortly thereafter.  my apologies for the delay.

**Comment by JamesAwesome** [comment]
No need to apologize! Thank you for keeping me posted though, I just wanted to make sure somebody was hacking at it, if not I would have volunteered to lend a hand. :smile:

**Comment by st-isidore-de-seville** [comment]
@JamesAwesome, here is the first one for the docker yum repository https://supermarket.chef.io/cookbooks/yum-docker

**Comment by st-isidore-de-seville** [comment]
@JamesAwesome, here is the repo for the docker apt repository: https://github.com/st-isidore-de-seville/cookbook-apt-docker.  I just have to promote it to Supermarket this afternoon and I guess @someara will take it from there.

**Comment by st-isidore-de-seville** [comment]
https://supermarket.chef.io/cookbooks/apt-docker

**Comment by JamesAwesome** [comment]
:+1: awesome, thank you @st-isidore-de-seville !

**Comment by someara** [comment]
Excellent. I'll take a look at these later this week!

-s

**Comment by someara** [comment]
Just took a look at these cookbooks. Great job!
I'll start utilizing these in the next major release. Thanks!

-s

**Comment by st-isidore-de-seville** [comment]
Thanks @someara.  I greatly appreciate it!

**Comment by drazzib** [comment]
Hi !

It would be really nice to use official debian packages provided by Docker Inc.
This should allow reuse of their provided SysvInit scripts (/etc/init.d and /etc/default/docker) which will simply this cookbook !

Regards,

**Comment by someara** [comment]
Linking to #520 where @chasebolt suggests using the get.docker.com script

**Comment by chasebolt** [comment]
:+1:

**Comment by someara** [comment]
Making moves on this... 
@st-isidore-de-seville heads up, PRs incoming for apt-docker and yum-docker

**Comment by st-isidore-de-seville** [comment]
Thanks @someara!  Taking a look at this currently.

**Comment by st-isidore-de-seville** [comment]
Hey @someara.  Since both PRs were similar in nature, I attached some questions to one of them.  Mostly it is just for learning on my part since I feel I am still new to this community and eco-system.  I am also resolving some the failed Travis-CI builds and once I can resolve them, I will merge them and promote to the Supermarket.  Thanks again!

**Comment by st-isidore-de-seville** [comment]
Hey @someara, I was able to fix my build issues and these have been promoted to the Supermarket.

**Comment by someara** [comment]
Excellent. Thanks!

-s

**Comment by st-isidore-de-seville** [comment]
@someara, I see this has been added but a quick question ... The https://get.docker.com/ appears to do more than just install the package.  It does some other configuration on the system.  See example below:

```
# aufs is preferred over devicemapper; try to ensure the driver is available.
			if ! grep -q aufs /proc/filesystems && ! $sh_c 'modprobe aufs'; then
				if uname -r | grep -q -- '-generic' && dpkg -l 'linux-image-*-generic' | grep -q '^ii' 2>/dev/null; then
					kern_extras="linux-image-extra-$(uname -r) linux-image-extra-virtual"

					apt_get_update
					( set -x; $sh_c 'sleep 3; apt-get install -y -q '"$kern_extras" ) || true

					if ! grep -q aufs /proc/filesystems && ! $sh_c 'modprobe aufs'; then
						echo >&2 'Warning: tried to install '"$kern_extras"' (for AUFS)'
						echo >&2 ' but we still have no AUFS.  Docker may not work. Proceeding anyways!'
						( set -x; sleep 10 )
					fi
				else
					echo >&2 'Warning: current kernel is not supported by the linux-image-extra-virtual'
					echo >&2 ' package.  We have no AUFS support.  Consider installing the packages'
					echo >&2 ' linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.'
					( set -x; sleep 10 )
				fi
			fi
```

I am wondering if this logic should also be replicated in this cookbook.  I can help out if needed by just wanted to get your thoughts?

**Comment by someara** [comment]
Nope. Cgroups and storage drivers are out of scope. 

They're a loosely coupled dep and should be set up with other cookbooks if needed. Modern Linux comes with this stuff enabled out of the box.

**Comment by someara** [comment]
That being said, I'm very happy to close this issue. =)

2.2.0 now uses the docker_installation_script resource by default, and has docker_installation_package available.

-s

**Comment by st-isidore-de-seville** [comment]
Thanks again @someara for all of your hard work on this!  Please let me know if I can help out in the future!
