### ISSUE TITLE
docker_container resources with sensitve(true) should not log their properties

### ISSUE THREAD

**Issue by b-dean** [someara/chef-docker#509]
One of the properties on all chef resources is `sensitive`, the [chef docs for this property](https://docs.chef.io/resources.html#properties) indicate that its purpose is to

> Ensure that sensitive resource data is not logged by the chef-client.

The reason this matters is I have containers where the environment variables contain passwords I've read from encrypted data bag items. For example:

```ruby
docker_container 'foo' do
  env 'AWS_KEY=abcdef AWS_SECRET=1234'
  sensitive true
end
```

would ignore the `sensitive` and output something like this to the log:

```
- create foo
-   set container_name               to "foo"
-   set env                          to ["AWS_KEY=abcdef AWS_SECRET=1234"]
```

That seems bad.

**Comment by chasebolt** [comment]
this change relies on a change for compat_resource cookbook and chef to be resolved.

https://github.com/chef-cookbooks/compat_resource/pull/4
https://github.com/chef/chef/pull/4054

**Comment by someara** [comment]
@jkeiser can you confirm that this is a bug in the compat_resource cookbook?

**Comment by someara** [comment]
Closing this for for lack of actionability...

Recreated in compat_resource for reference
https://github.com/chef-cookbooks/compat_resource/issues/6
