### ISSUE TITLE
SSL_connect error when running docker_service with host set

### ISSUE THREAD

**Issue by 5f6b3fb8** [someara/chef-docker#526]
I'm trying to use the docker cookbook to setup a swarm. When creating the docker service, I set the host attribute as follows, per documentation: https://docs.docker.com/swarm/install-manual/

    docker_service 'default' do
      host 'tcp://0.0.0.0:2375'
      action [:create, :start]
    end

The converge bombs out with the following error:
    ================================================================================
    Error executing action `create` on resource 'docker_service_systemd[default]'
    ================================================================================

    Excon::Errors::SocketError
    --------------------------
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError)

However, if I then log into the box using Kitchen, and run the info command with the host specified, the service was created and appears to be running:

    [root@swarm-manager-centos71 ~]# docker -H tcp://0.0.0.0:2375 info
    Containers: 0
    Images: 0
    Storage Driver: devicemapper
    Pool Name: docker-253:0-135301711-pool
    Pool Blocksize: 65.54 kB
    ....

I can also issue other docker commands like pull, run, etc.

Some details:
OS: CentOS Linux 7 (Core) - From vagrant box: boxcutter/centos71
Docker Cookbook Version: 2.1.2
ChefDK: 0.8.0

**Comment by chasebolt** [comment]
this is related to tls_client_cert/key not being set for docker_service. can you output the dump of `env | grep DOCKER`? i am curious to know if DOCKER_CERT_PATH is set for you.

**Comment by 5f6b3fb8** [comment]
env | grep DOCKER did not return any results.

The same is true if I leave out the host parameter, however this converges w/o any SSL_Connect errors:

    docker_service 'default' do
      action [:create, :start]
    end

**Comment by 5f6b3fb8** [comment]
Sharing a workaround I came up with

Starting the service workaround

    docker_service 'default' do
      host 'tcp://0.0.0.0:2375'
      action [:create]
    end

    #starting the service like this doesn't bomb out with SSL connect error
    service 'docker' do
      action [:start]
    end

The following commented code is how I want to join the swarm, the following execute resource is how I successfully joined the swarm

    #this doesn't work
    #docker_container 'swarm_agent' do
      #  repo 'swarm'
      #  host 'tcp://0.0.0.0:2375'
      #  restart_policy 'always'
      #  command "join --addr=172.31.255.2:2375 token://3fdd61dfd70b48f2a7c3e1652baa8c72"
      #  action :run
    #end

    execute 'swarm_agent' do
     command "docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=172.31.255.2:2375 token://3fdd61dfd70b48f2a7c3e1652baa8c72"
    end

I can now log in and see the swarm node

> kitchen login swarm-manager-centos71
> Last login: Tue Oct 20 23:26:56 2015 from 10.0.2.2
> Welcome to your Packer-built virtual machine.
> [vagrant@swarm-manager-centos71 ~]$ sudo su -
> [root@swarm-manager-centos71 ~]# docker -H tcp://0.0.0.0:2375 ps
> CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                     NAMES
> 37f48ae020f1        swarm               "/swarm manage token:"   About a minute ago   Up About a minute   0.0.0.0:32768->2375/tcp   hungry_kilby
> b1cff2926774        swarm               "/swarm join --addr=1"   About a minute ago   Up About a minute   2375/tcp                  ecstatic_bhaskara
> [root@swarm-manager-centos71 ~]# docker -H tcp://0.0.0.0:32768 info
> Containers: 2
> Images: 1
> Role: primary
> Strategy: spread
> Filters: affinity, health, constraint, port, dependency
> Nodes: 1
>  swarm-manager-centos71: 172.31.255.2:2375
>   └ Containers: 2
>   └ Reserved CPUs: 0 / 2
>   └ Reserved Memory: 0 B / 2.847 GiB
>   └ Labels: executiondriver=native-0.2, kernelversion=3.10.0-229.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
> CPUs: 2
> Total Memory: 2.847 GiB
> Name: 37f48ae020f1
