### ISSUE TITLE
redeploy signals, timeout options

### ISSUE THREAD

**Issue by KostyaSha** [someara/chef-docker#527]
It is very critical to do redeploy/restart/stop/kill/etc with timeout either it may corrupt database with kill signal.

**Comment by KostyaSha** [comment]
https://labs.ctl.io/gracefully-stopping-docker-containers/

**Comment by someara** [comment]
Notes from IRC

```
KostyaSha> someara, prometheus flushes in memory data every 5 min, so redeploy kills it. Postgres will have warnings in error log
```

**Comment by KostyaSha** [comment]
@chasebolt pointed to signal and non 1 PID. I may mistake that cookbook doesn't support it.
