### ISSUE TITLE
Fix remote host over TLS on docker_image and docker_container resources

### ISSUE THREAD

**Issue by 5f6b3fb8** [someara/chef-docker#529]
I have installed the docker service with the following resource:

```ruby
    docker_service 'default' do
      host 'tcp://0.0.0.0:2375'
      action [:create, :start]
    end
```

I'm now trying to run a container with the host attribute set with the following resource:

```ruby
    docker_container 'swarm_agent' do
      repo 'swarm'
      host 'tcp://0.0.0.0:2375'
      restart_policy 'always'
      command "join --addr=#{ipaddress}:2375 token://#{cluster_id}"
      action :run
    end
```

And I'm getting the following error:

    ================================================================================
    Error executing action `run` on resource 'docker_container[swarm_agent]'
    ================================================================================

    Excon::Errors::SocketError
    --------------------------
    No such file or directory - connect(2) for /var/run/docker.sock (Errno::ENOENT)

Interestingly, docker_image seemed to pull successfully with the following resource, so is it handling the host attribute differently then docker_container?

    docker_image 'swarm' do
      host 'tcp://0.0.0.0:2375'
      action :pull_if_missing
    end

**Comment by someara** [comment]
Apparently so. I'm currently in the process of setting up some tests to sort all this out.
Stay tuned.

-s

**Comment by chasebolt** [comment]
you can't set a 0.0.0.0 for a host ip on a docker_container. you need to set a valid ip that you want the docker_container to communicate with. 127.0.0.1 if the docker daemon is local would be valid.

**Comment by 5f6b3fb8** [comment]
I'm getting the same error when I set 127.0.0.1, does this look correct?

    docker_container 'swarm_agent' do
      repo 'swarm'
      host 'tcp://127.0.0.1:2375'
      restart_policy 'always'
      command "join --addr=#{ipaddress}:2375 token://#{cluster_id}"
      action :run
    end

Also, I can run the following execute and this works as expected:

    execute 'swarm_agent' do
      command "docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=#{ipaddress}:2375 token://#{node['vertafore_docker']['swarm']['cluster_id']}"
    end

**Comment by chasebolt** [comment]
what version of the docker cookbook are you using?

**Comment by someara** [comment]
@chasebolt I just updated master so that the docker_service in docker_test::default sets itself up to listen  on both the local socket and tcp://127.0.0.1:2376

uncommenting 'docker_container[host_override]' results in a failure (which I expected).

I'm currently trying to see if I can get it to work via ENV manipulation, which would be handy I guess, but ultimately this feature won't be complete until we have the tls_whatever properties on all the resources

https://github.com/someara/chef-docker/blob/5f05da9706e6616b7d2b6be84056d21e8eb51a91/libraries/docker_service.rb#L52-L57

**Comment by 5f6b3fb8** [comment]
My examples are based on docker 2.1.5 after my previous issue was fixed #526

**Comment by someara** [comment]
Okay... as of 2.1.6, we now have integration tests passing for docker_image and docker_container

Image

https://github.com/someara/chef-docker/blob/cd3aa4e55a91a990b08c14d2110058a810b427ba/test/cookbooks/docker_test/recipes/image.rb#L35-L43

Container
https://github.com/someara/chef-docker/blob/cd3aa4e55a91a990b08c14d2110058a810b427ba/test/cookbooks/docker_test/recipes/container.rb#L852-L861

You may need to either disable TLS verification, or specify the paths to your CA and client certs on the resource.

Let me know if this works for you.

-s

**Comment by 5f6b3fb8** [comment]
The code is a little difficult for me to understand, but it seems like the problem might be in one of the docker api gems. This is with version 2.1.6. I checked the location and there is no docker.sock file, there is a docker.pid file.

```
================================================================================
Error executing action `run` on resource 'docker_container[swarm_agent]'
================================================================================

Excon::Errors::SocketError
--------------------------
No such file or directory - connect(2) for /var/run/docker.sock (Errno::ENOENT)

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/unix_socket.rb:14:in `connect_nonblock'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/unix_socket.rb:14:in `connect'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/socket.rb:28:in `initialize'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:385:in `new'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:385:in `socket'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
ault/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:40:in `request'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/tmp/kitchen/cache/cookbooks/docker/files/default/vendor/gems/docker-api-1.22.4/lib/docker/container.rb:241:in `get'
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:121:in `block (2 levels) in <class:DockerContainer>'
/tmp/kitchen/cache/cookbooks/docker/libraries/helpers_base.rb:66:in `call'
/tmp/kitchen/cache/cookbooks/docker/libraries/helpers_base.rb:66:in `with_retries'
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:121:in `block in <class:DockerContainer>'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource/action_class.rb:57:in `load_current_resource'
```

**Comment by someara** [comment]
oooooh. I see what's going on..
You're not starting your service with a socket.

```
docker_service 'default' do
  host ['unix:///var/run/docker.sock', 'tcp://127.0.0.1:2376'] 
  action [:create, :start]
end
```

**Comment by someara** [comment]
Here's an example of starting one with a both a socket and TLS

https://github.com/someara/chef-docker/blob/cd3aa4e55a91a990b08c14d2110058a810b427ba/test/cookbooks/docker_test/recipes/default.rb

**Comment by chasebolt** [comment]
@5f6b3fb8 working on this. I do see an issue but haven't been able to crack it yet. Your configured container is valid.

```ruby
docker_container 'swarm_agent' do
  repo 'swarm'
  host 'tcp://127.0.0.1:2375'
  restart_policy 'always'
  command "join --addr=#{ipaddress}:2375 token://#{cluster_id}"
  action :run
end
```

**Comment by someara** [comment]
I renamed the issue in haste after mis-groking this, assuming it was the remote TLS bug.
Somebody feel free to fix the issue title so it's more accurate

**Comment by chasebolt** [comment]
you and 5f6b3fb8 are the only two that can fix the title :stuck_out_tongue_closed_eyes: 

should just be titled "docker_container host property failing"
