### ISSUE TITLE
Docker service, remote filesystems and broken container bindmounts on reboot

### ISSUE THREAD

**Issue by jperville** [someara/chef-docker#536]
On our platform at PerfectMemory, we deploy our applications as docker containers. Some of our applications rely on a shared filesystem to be accessible from inside the container (local filesystem does not work when deploying on a cluster).

We implement this feature by:
 1. mounting a remote filesystem on the host, for us it is usually mounted to /ceph
 2. running containers with a bind-mount the host-mounted remote filesystem, eg. `docker run -v /ceph:/ceph`

This works very well if the remote filesystem is mounted on the host before we start creating the containers. However, when the system reboots, we run in a race condition where:
 1. docker creates the container before the remote filesystem is mounted on the host (in other words, it is bind-mounting a /ceph which is probably an empty directory)
 2. the operating system attempts to mount the remote filesystem

If the host mountpoint directory is still empty when the operating system mounts the remote filesystem then the mount will succeed but the containers will not be seeing the expected data in /ceph. If the containers persist stuff then this stuff will stay in the shadowed mountpoint directory on the host.

If the host mountpoint directory is not empty at the time the operating system tries to mount the remote filesystem (eg. because containers have persisted stuff in the directory) then the mount attempt may fail (this is the case with CephFS, which refuses to mount over a non-empty directory). Then future chef-client runs will fail because the LWRP to mount the CephFS to /ceph is converged early in the run list.

The proper fix would be to make starting the docker daemon depend on availability of all filesystems on the machine, or at least all the filesystems that we intend to export to containers with bind-mounts.

I have checked the Upstart template from this cookbook; in https://github.com/someara/chef-docker/blob/master/templates/default/upstart/docker.conf.erb#L3 we can see that the docker service runs as soon as the local-filesystems are available (without waiting for remote filesystems). I changed that line to `start on (filesystem and net-device-up IFACE!=lo)` and now docker waits on all filesystems to be available (including remote filesystems).

I reboot the server and magic, my containers are not broken anymore. This is still a bit heavy handed because the fstab may have a lot of entries which we may not be using with containers, but I believe that not having docker run is better than having it run containers with broken bindmounts.

Would it be possible to use my workaround in a future version of this cookbook? I would submit a PR but it would be upstart only, I don't know how to do the equivalent on systemd and other init systems.

**Comment by jperville** [comment]
I have reported the issue to docker: docker/docker#17485 but I'd still like this implement the trivial workaround in the cookbook here.

Getting this fixed is critical to us, because not having the workaround means that each time a server reboots we need to fix manually by:
 - removing all affected containers
 - rm -rf /ceph/* if /ceph is not mounted
 - recreating all the containers
Which is very tedious.

I'd rather have no docker daemon running after a reboot (until chef fixes the mounts) than having docker daemon start and run broken containers that I will have to fix by hand.

**Comment by someara** [comment]
Sounds good to me. Merging!

**Comment by jperville** [comment]
Thanks so much @someara.
