### ISSUE TITLE
Missing runit support

### ISSUE THREAD

**Issue by sandoracs** [someara/chef-docker#538]
Hi!

This cookbook used to support runit for provisioning containers. I wonder why this feature was removed. Can anybody help me understand the reason behind it?

**Comment by someara** [comment]
Before Docker 1.2.0, runit (or upstart/systemd/whatever) was used to manage the running state of a container and for surviving reboots. The old `docker_container` implementation used a service script generated a docker CLI command and shoved it into a file. 

After Docker 1.2.0, the `docker_service

```ruby
docker_container 'foo_server' do
  restart_policy 'on-failure'
  action :create
end
```

**Comment by sandoracs** [comment]
It is clear now. Thank you very much.
