### ISSUE TITLE
Version ignored when docker_service used script installation

### ISSUE THREAD

**Issue by manuelmazzuola** [someara/chef-docker#543]
Hi,
Is the version attribute ignored in the docker_service resource ?

Tonight in mine timezone docker 1.9.0 has been released.
Yesterday this test installs docker 1.8.3
This morning this test installs docker 1.9.0

I realized it when this morning tests fail because https://github.com/someara/chef-docker/issues/542

```
docker_service 'default' do
  tls false
  storage_driver node['docker']['storage_driver']
  group node['docker']['group_members']
  version '1.8.3'
  install_method 'auto'
  service_manager 'auto'
  auto_restart true
  # log_driver 'syslog'
  action [:create, :start]
end
```

```
ubuntu@test-cd-docker:/tmp/kitchen/cookbooks/cd-docker/recipes$ sudo docker info
Containers: 0
Images: 10
Server Version: 1.9.0
```

**Comment by someara** [comment]
Hello! This is definitely a bug... 

Here is what is happening - the "auto" install_method is using the docker_installation_script resource under the hood, which does not support the "version" property.

For now, either specify "binary" or "package install_method, or use the docker_installation_package or docker_installation_binary resources directly,

The long term fix is going to have docker_service resource do sanity checking for mutually exclusivity.

-s

**Comment by manuelmazzuola** [comment]
:+1:

**Comment by someara** [comment]
Closing this here, referencing #557.
