### ISSUE TITLE
Failed :start for docker_service

### ISSUE THREAD

**Issue by joshskains** [someara/chef-docker#544]
Just trying to make a basic Docker Host role:

docker_service 'default' do
  action [:create, :start]
end

Fails:
================================================================================
    Error executing action `start` on resource 'docker_service[default]'
    ================================================================================
    
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option action must be equal to one of: nothing!  You passed :start.

**Comment by chasebolt** [comment]
please post your version of the cookbook and chef-client

**Comment by joshskains** [comment]
chef-client 12.3.0
chef-docker 2.2.3

**Comment by chasebolt** [comment]
sorry what os and version as well?

**Comment by agarat** [comment]
I reported this in #533, my solution was to update chef-client to 12.5.1 since I couldn't find another workaround for this.

**Comment by someara** [comment]
I'm pretty sure this is an old compat_resource causing issues.
chef-docker 2.2.5 pins >= to a known working version.

Closing for now, please re-open if this persists.
