### ISSUE TITLE
docker api 1.21 image id isn't consistent

### ISSUE THREAD

**Issue by chasebolt** [someara/chef-docker#550]
This same code shows image.get and image.create no longer returns the same id for the same image. We are currently using this id to determine if a new image was pulled and if so mark the resource as updated. We need to figure out a new way to determine the handling of this resource update.

```ruby
require 'docker'

image_c = Docker::Image.get('alpine')
image_g = Docker::Image.create('fromImage' => 'alpine')

puts "create: #{image_c.id}"
puts "get: #{image_g.id}"

# create: f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0
# get: latest
```

Linking docker-api issue https://github.com/swipely/docker-api/issues/333

**Comment by someara** [comment]
Hacked around by making an extra API call here: https://github.com/someara/chef-docker/commit/15db7133e408ded9ec463c3ef6211b9bbb5585c1

Released as 2.2.6

**Comment by chasebolt** [comment]
Haha hacks. LGTM

**Comment by tlunter** [comment]
Feel free to revert the hack, the API now does this itself.

**Comment by chasebolt** [comment]
Can you elaborate on this @tlunter? What is "does this"?

**Comment by chasebolt** [comment]
perfect! i see `.create` is returning an image id now. thanks for updating this issue!

**Comment by tlunter** [comment]
Sorry about the vagueness :D
