### ISSUE TITLE
docker_container :create appears to redeploy my volume container

### ISSUE THREAD

**Issue by 5f6b3fb8** [someara/chef-docker#551]
Per the docker cookbook documentation

>>> :create - Creates the container but does not start it. Useful for Volume containers.

This sounds like what I want - to create a volume container in my swarm.

So I create a resource like this:

    docker_container 'jenkins_master_data' do
      repo 'jenkins'
      tag '1.609.3'
      host 'tcp://0.0.0.0:2377' # this is converging on the swarm manager host, listening on 2377
      command 'true'
      action :create
    end

I converge, and this works great. Another container consumes the volume container, writes to the volume, and the files end up in the volume container's host path. Then I converge again and the container has a new ID and new volume path upon inspect. Am I using the create action correctly? Does it need to be paired with other actions or guards?

**Comment by 5f6b3fb8** [comment]
This is on docker cookbook v2.2.2

**Comment by someara** [comment]
Is this on Docker 1.9?
As of right now, it has a bunch of bugs that need to be worked out.

**Comment by 5f6b3fb8** [comment]
Yup, 1.9.0. I should be able to workaround this issue.

**Comment by someara** [comment]
I'd lock to 1.8.3 until this cookbook officially supports 1.9.x.
There are a lot more strange things going in addition to this.

**Comment by someara** [comment]
There are few fixes for 1.9 in 2.2.6. I ran the test-kitchen suites twice and haven't seen any redeploys, so this should be fixed up.

Please re-open if this is still an issue.

-s

**Comment by 5f6b3fb8** [comment]
Looks like that was it. 2.2.6 is working for me, thanks!
