### ISSUE TITLE
Specify API version when making requests

### ISSUE THREAD

**Issue by someara** [someara/chef-docker#552]
Apparently you can prefix calls to the Remote API with version information... '/1.17/whatever' 
We should take advantage of this to guard against Docker's ever evolving API.

Not sure if the docker-api gem makes this easy/possible.. simply making a note of it here.

-s

**Comment by chasebolt** [comment]
Good idea. This would help with keeping this cookbook stable through docker
upgrades.

I'll take a look at docker-api gem and see what we can do.

**Comment by someara** [comment]
Thanks!

**Comment by chasebolt** [comment]
Looked into the docker-api gem and it is already passing version 1.16 for the api calls.

https://github.com/swipely/docker-api/blob/master/lib/docker/connection.rb#L83
https://github.com/swipely/docker-api/blob/master/lib/docker/version.rb#L6

**Comment by someara** [comment]
Welp.
