### ISSUE TITLE
--tlsverify=false still implies --tls which causes an error when no key pair is generated

### ISSUE THREAD

**Issue by AnalogJ** [someara/chef-docker#558]
### Environment: 
- Ubutu 14
- Docker 1.9.0
- Chef-Docker Cookbook 2.2.7

### Scenario:
Trying to install latest Docker (1.9.0)

### Steps to Reproduce:

I just tried to install docker using a simple 

	docker_service 'default' do
	  action [:create, :start]
	end

And I got an error stating the docker service could not start.
I checked the /var/log/docker.log file but it was empty, however the /var/log/upstart/docker.log file had the following entries repeated over and over:

	time="2015-11-12T03:01:49.904815299Z" level=fatal msg="Could not load X509 key pair (cert: \"\", key: \"\"): open : no such file or directory" 
	Docker is up

I took a look at the docker issues and it seems that this change occured in docker v1.8.0. (https://github.com/docker/docker/pull/15191)

Everything works correctly when I manually run:

    /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://127.0.0.1:2376 --pidfile=/var/run/docker.pid

But fails when I run:

    /usr/bin/docker daemon -H unix:///var/run/docker.sock -H tcp://127.0.0.1:2376 --pidfile=/var/run/docker.pid --tlsverify=false

### Fix 

The fix seems to be modifying the following line:

	opts << "--tlsverify=#{tls_verify}" unless tls_verify.nil?

Found in:
https://github.com/someara/chef-docker/blob/master/libraries/helpers_service.rb#L115
https://github.com/someara/chef-docker/blob/master/libraries/helpers_service.rb#L156

To:

	opts << "--tlsverify=#{tls_verify}" unless tls_verify

Which is consistent with the other flags.

**Comment by chasebolt** [comment]
The issue is in the helpers_base. It needs to return nil for both tls and tls_verify.

**Comment by AnalogJ** [comment]
Oh and setting the tls_verify property to `nil` produces an error as well. 
	docker_service 'default' do
	  tls_verify nil
	  action [:create, :start]
	end

	==> default: Chef::Exceptions::ValidationFailed
	==> default:   
	==> default: ----------------------------------
	==> default:   
	==> default: Option tls_verify must be one of: true, false!  You passed nil.

**Comment by chasebolt** [comment]
The nil would have to be in the helpers_base. Nil isn't a valid user
setting for this property.

**Comment by jperville** [comment]
Thanks @chasebolt for the fix, looking forward for the merge!

**Comment by AnalogJ** [comment]
thanks for the help guys :)
